# yaml-language-server: $schema=https://rdmr.eu/sparql-query-runner/schema.json
version: v5
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  owl: http://www.w3.org/2002/07/owl#
  imbor-domeinwaarde: https://data.crow.nl/imbor/id/domeinwaarden/
  imbor: https://data.crow.nl/imbor/def/
  imbor-term: https://data.crow.nl/imbor/term/
  imbor-refmodels: https://data.crow.nl/imbor-ref/def/
  imbor-meta: https://data.crow.nl/imbor/aanvullend-metamodel/
  imbor-refmodels-id: https://data.crow.nl/imbor-ref/id/
  imbor-mim: https://data.crow.nl/imbor/mim/
  quantitykind: http://qudt.org/vocab/quantitykind/
  nen2660: https://w3id.org/nen2660/def#
  nen2660-term: https://w3id.org/nen2660/term#
  nen3610: http://definities.geostandaarden.nl/def/nen3610#
  mim: http://bp4mc2.org/def/mim#
  unit: http://qudt.org/vocab/unit/
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  xsd: http://www.w3.org/2001/XMLSchema#
  dct: http://purl.org/dc/terms/
  dc: http://purl.org/dc/elements/1.1/
  geo: http://www.opengis.net/ont/geosparql#
  sh: http://www.w3.org/ns/shacl#
  skos: http://www.w3.org/2004/02/skos/core#
  dash: http://datashapes.org/dash#
  coll: https://data.crow.nl/rest-api/id#
  restapi: https://data.crow.nl/rest-api/def#
jobs:
  converteer-accessdb:
    steps:
      - shell: rdfjs-source-msaccess --input data/IMBOR-2022-03.accdb --output .cache/imbor-latest.nq --mode csv --datatypes easy-sparql

  stap-1-data-opbouw:
    sources:
      - file: .cache/imbor-latest.nq
    steps:
      - update: src/transformations/addendum-geometrie.ru
      - update: src/transformations/attributen.ru
      - update: src/transformations/attribuutshapes.ru
      - update: src/transformations/enumeratietypes-domeinwaarden.ru
      - update: src/transformations/enumeratietypes-gesloten.ru
      - update: src/transformations/enumeratietypes-klasses.ru
      - update: src/transformations/imbor-metaontologie.ru
      - update: src/transformations/informatiemodellen.ru
      - update: src/transformations/klassen-definities.ru
      - update: src/transformations/klassen-hierarchie.ru
      - update: src/transformations/minimale-dataset.ru
      - update: src/transformations/oagbd.ru
      - update: src/transformations/referentiemodel-attributen.ru
      - update: src/transformations/referentiemodel-domeinwaarden.ru
      - update: src/transformations/referentiemodel-mapping.ru
      - update: src/transformations/referentiemodel-mapping-delete.ru
      - update: src/transformations/referentiemodel-mapping-delete-ref.ru
      - update: src/transformations/referentiemodel-mapping-delete-all.ru
      - update: src/transformations/referentiemodel-objecttypen.ru
      - update: src/transformations/semantische-relaties.ru
      - update: src/transformations/termen-en-collecties.ru
      - update: src/transformations/klassen-hierarchie-skos.ru
      - update: src/transformations/unit-quantity-kind.ru
      - update: src/transformations/vakdisciplines.ru
      - update: src/transformations/owl-ontologies.ru
      - update: src/transformations/scheme-skos.ru
    targets:
      - file: .cache/post-stap-1-data-opbouw.nq

  stap-2-hernoemen:
    sources:
      - file: .cache/post-stap-1-data-opbouw.nq
    steps:
      - update: src/transformations/hernoemen-refurls.ru
      - update: src/transformations/hernoemen-refurls.ru
      - update: src/transformations/hernoemen-refurls.ru
      - update: src/transformations/vocab-hierarchie-1.ru
      - update: src/transformations/vocab-hierarchie-2.ru
      - update: src/transformations/vocab-hierarchie-3.ru
    targets:
      - file: .cache/post-stap-2-hernoemen.nq

  stap-3-mim:
    sources:
      - file: .cache/post-stap-2-hernoemen.nq
    steps:
      - update: src/transformations/mim-klasses.ru
      - update: src/transformations/mim-attributen.ru
      - update: src/transformations/mim-relaties.ru
      - update: src/transformations/mim-enumeraties.ru
      - update: src/transformations/mim-domeinwaarden.ru
      - update: src/transformations/mim-datatype.ru
      - update: src/transformations/mim-generalisaties.ru
    targets:
      - file: .cache/post-stap-3-mim.nq

  stap-4-metadata:
    sources:
      - file: .cache/post-stap-3-mim.nq
    steps:
      - update: src/transformations/versie-publicatie-graaf-info.ru
      - update: src/transformations/shacl-messages-and-rules.ru
      - update: src/transformations/qualifiedValueShape-replace-qualifiedMaxMin-991.ru
      - update: src/transformations/qualifiedValueShape-min-constraint.ru
    targets:
      - file: .cache/stap-4-metadata.nq

  stap-5-outputs-zonder-externe-ontologieen:
    sources:
      - file: .cache/stap-4-metadata.nq
    targets:
      - file: data/imbor-vocabulaire.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/term/"

      - file: data/imbor-kern.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/def/"

      - file: data/imbor-domeinwaarden.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/id/domeinwaarden/"

      - file: data/imbor-aanvullend-metamodel.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/aanvullend-metamodel"

      - file: data/imbor-informatief.trig
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/addendum/oagbd"
            - "https://data.crow.nl/imbor/addendum/geometrie"
            - "https://data.crow.nl/imbor/addendum/minimale-dataset"
            - "https://data.crow.nl/imbor/addendum/referentiemodellen"
            - "https://data.crow.nl/imbor/mim"

      - file: data/imbor-informatief_LacesUpload.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/addendum/oagbd"
            - "https://data.crow.nl/imbor/addendum/geometrie"
            - "https://data.crow.nl/imbor/addendum/minimale-dataset"
            - "https://data.crow.nl/imbor/addendum/referentiemodellen"
            - "https://data.crow.nl/imbor/mim"

      - file: data/imbor-rest-api-linkset.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/addendum/rest-api"

  stap-6-outputs-met-externe-ontologieen:
    sources:
      - file: .cache/stap-4-metadata.nq
    targets:
      - file: data/imbor-volledig-onto-verkenner.ttl
        with:
          only-graphs:
            - https://data.crow.nl/imbor/term/
            - https://data.crow.nl/imbor/def/
            - https://data.crow.nl/imbor/id/domeinwaarden/
            - https://data.crow.nl/imbor/aanvullende-modellen
            - https://data.crow.nl/imbor/aanvullend-metamodel
            - https://data.crow.nl/imbor/addendum/oagbd
            - https://data.crow.nl/imbor/addendum/geometrie
            - https://data.crow.nl/imbor/addendum/minimale-dataset
            - https://data.crow.nl/imbor/addendum/referentiemodellen
            - https://data.crow.nl/imbor/mim

      - file: data/imbor-gecombineerd-tbv-shaclvalidatie.ttl
        with:
          only-graphs:
            - https://data.crow.nl/imbor/def/
            - https://data.crow.nl/imbor/id/domeinwaarden/
            - https://data.crow.nl/imbor/aanvullende-modellen
            - https://data.crow.nl/imbor/aanvullend-metamodel
