# yaml-language-server: $schema=https://rdmr.eu/sparql-query-runner/schema.json
version: v5
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  owl: http://www.w3.org/2002/07/owl#
  skos: http://www.w3.org/2004/02/skos/core#
  sh: http://www.w3.org/ns/shacl#
  xsd: http://www.w3.org/2001/XMLSchema#
  prov: http://www.w3.org/ns/prov#
  dash: http://datashapes.org/dash#
  dct: http://purl.org/dc/terms/
  geo: http://www.opengis.net/ont/geosparql#
  quantitykind: http://qudt.org/vocab/quantitykind/
  qudt: http://qudt.org/schema/qudt/
  unit: http://qudt.org/vocab/unit/
  nen2660: https://w3id.org/nen2660/def#
  nen2660-term: https://w3id.org/nen2660/term#
  nen3610: http://modellen.geostandaarden.nl/def/nen3610-2022#
  nen3610-beg: http://definities.geostandaarden.nl/nen3610-2022/id/begrip/
  nen3610-col: http://definities.geostandaarden.nl/nen3610-2022/id/collectie/
  nen3610-ont: http://modellen.geostandaarden.nl/def/nen3610/
  nen3610-sh: http://modellen.geostandaarden.nl/nen3610/id/shape/
  mim: http://bp4mc2.org/def/mim#
  net: http://inspire.ec.europa.eu/ont/net#
  tooi-ont: https://identifier.overheid.nl/tooi/def/ont/
  imbor: https://data.crow.nl/imbor/def/
  imbor-term: https://data.crow.nl/imbor/term/
  imbor-refmodels: https://data.crow.nl/imbor-ref/def/
  imbor-refmodels-id: https://data.crow.nl/imbor-ref/id/
  imbor-domeinwaarde: https://data.crow.nl/imbor/id/domeinwaarden/
  imbor-mim: https://data.crow.nl/imbor/mim/
  imbor-meta: https://data.crow.nl/imbor/aanvullend-metamodel/
  crow_change: https://data.crow.nl/change/def/
  imbor_change_log: https://data.crow.nl/change/log/imbor/id/
  restapi: https://data.crow.nl/rest-api/def#
  coll: https://data.crow.nl/rest-api/id#
  as: https://www.w3.org/ns/activitystreams/
  gwsw: http://data.gwsw.nl/1.6/totaal/
  sml: https://w3id.org/sml/def#

jobs:
  converteer-accessdb:
    steps:
      - shell: >
          rdfjs-source-msaccess
          --input data/msaccess/IMBOR-development.accdb
          --output .cache/imbor-latest.nq
          --mode csv
          --datatypes easy-sparql

  stap-0-clear-all-graphs:
    sources:
      - sparql: http://localhost:7200/repositories/imbor-development/statements
    steps:
      - update: >
          CLEAR ALL

  stap-0-upload-imbor-csv:
    steps:
      - http-request: http://localhost:7200/repositories/imbor-development/statements
        with:
          method: PUT
          body-file: .cache/imbor-latest.nq
          headers:
            Content-Type: application/n-quads

  stap-1-data-opbouw:
    sources:
      - sparql: http://localhost:7200/repositories/imbor-development/statements
    steps:
      - update: src/transformations/addendum-geometrie.ru
      - update: src/transformations/attributen.ru
      - update: src/transformations/attribuutshapes.ru
      - update: src/transformations/enumeratietypes-domeinwaarden.ru
      - update: src/transformations/enumeratietypes-enumeratielijst.ru
      - update: src/transformations/enumeratietypes-suggestielijst.ru
      - update: src/transformations/imbor-metaontologie.ru
      - update: src/transformations/informatiemodellen.ru
      - update: src/transformations/informatiemodellen-imborguid.ru
      - update: src/transformations/klassen-definities.ru
      - update: src/transformations/materialen.ru
      - update: src/transformations/hierarchie.ru
      - update: src/transformations/hierarchie-materialen.ru
      - update: src/transformations/oagbd.ru
      - update: src/transformations/semantische-relaties.ru
      - update: src/transformations/termen-en-collecties.ru
      - update: src/transformations/hierarchie-skos.ru
      - update: src/transformations/unit-quantity-kind.ru
      - update: src/transformations/vakdisciplines.ru
      - update: src/transformations/owl-ontologies.ru
      - update: src/transformations/scheme-skos.ru

  stap-2-hernoemen:
    sources:
      - sparql: http://localhost:7200/repositories/imbor-development/statements
    steps:
      - update: src/transformations/hernoemen-refurls.ru
      - update: src/transformations/hernoemen-refurls.ru
      - update: src/transformations/hernoemen-refurls.ru
      - update: src/transformations/vocab-hierarchie-1.ru
      - update: src/transformations/vocab-hierarchie-2.ru
      - update: src/transformations/vocab-hierarchie-3.ru

  stap-3-mim:
    sources:
      - sparql: http://localhost:7200/repositories/imbor-development/statements
    steps:
      - update: src/transformations/mim-klasses.ru
      - update: src/transformations/mim-attributen.ru
      - update: src/transformations/mim-relaties.ru
      - update: src/transformations/mim-enumeraties.ru
      - update: src/transformations/mim-domeinwaarden.ru
      - update: src/transformations/mim-datatype.ru
      - update: src/transformations/mim-generalisaties.ru
      - update: src/transformations/mim-datumopname.ru
      - update: src/transformations/mim-datumopname_relaties.ru

  stap-4-metadata:
    sources:
      - sparql: http://localhost:7200/repositories/imbor-development/statements
    steps:
      - update: src/transformations/versie-publicatie-graaf-info.ru
      - update: src/transformations/shacl-messages-and-rules.ru
      - update: src/transformations/qualifiedValueShape-replace-qualifiedMaxMin-991.ru
      - update: src/transformations/qualifiedValueShape-min-constraint.ru
      - update: src/transformations/logging.ru
      - update: src/transformations/logging-remove-not-existing.ru

  download-voor-gefilterde-export:
    steps:
      - http-request: http://localhost:7200/repositories/imbor-development/statements
        with:
          headers:
            Accept: application/n-quads
          destination: .cache/post-stap-4-metadata.nq

  stap-5-outputs-zonder-externe-ontologieen:
    sources:
      - file: .cache/post-stap-4-metadata.nq
    targets:
      - file: data/rdf/imbor-vocabulaire.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/term/"

      - file: data/rdf/imbor-kern.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/def/"

      - file: data/rdf/imbor-domeinwaarden.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/id/domeinwaarden/"

      - file: data/rdf/imbor-aanvullend-metamodel.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/aanvullend-metamodel/"

      - file: data/rdf/imbor-addendum-referentiemodellen.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/addendum/referentiemodellen/"

      - file: data/rdf/imbor-addendum-oagbd.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/addendum/oagbd/"

      - file: data/rdf/imbor-addendum-geometrie.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/addendum/geometrie/"

      - file: data/rdf/imbor-addendum-materie.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/addendum/materie/"

      - file: data/rdf/imbor-mim.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/mim/"

      - file: data/rdf/imbor-rest-api-linkset.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/imbor/addendum/rest-api/"

      - file: data/rdf/change_log_imbor.ttl
        with:
          only-graphs:
            - "https://data.crow.nl/change/log/imbor/"

  stap-6-laad-externe-ontologieen:
    sources:
      - sparql: http://localhost:7200/repositories/imbor-development/statements
    steps:
      - update: src/transformations/load-ext-ontologieen.ru
      - update: src/transformations/clean-up-qudt-mess.ru

  download-voor-export-incl-externe-ontologieen:
    steps:
      - http-request: http://localhost:7200/repositories/imbor-development/statements
        with:
          headers:
            Accept: application/n-quads
          destination: .cache/post-stap-6-ext-onto.nq

  stap-6-outputs-met-externe-ontologieen:
    sources:
      - file: .cache/post-stap-6-ext-onto.nq
    targets:
      - file: data/rdf/imbor-volledig-combigraph.ttl
        with:
          only-graphs:
            - https://data.crow.nl/imbor/term/
            - https://data.crow.nl/imbor/def/
            - https://data.crow.nl/imbor/id/domeinwaarden/
            - https://data.crow.nl/imbor/aanvullende-modellen/
            - https://data.crow.nl/imbor/aanvullend-metamodel/
            - https://data.crow.nl/imbor/addendum/oagbd/
            - https://data.crow.nl/imbor/addendum/geometrie/
            - https://data.crow.nl/imbor/addendum/materie/
            - https://data.crow.nl/imbor/addendum/referentiemodellen/
            - https://data.crow.nl/imbor/mim/

      - file: data/rdf/imbor-gecombineerd-tbv-shaclvalidatie.ttl
        with:
          only-graphs:
            - https://data.crow.nl/imbor/def/
            - https://data.crow.nl/imbor/id/domeinwaarden/
            - https://data.crow.nl/imbor/addendum/materie/
            - https://data.crow.nl/imbor/aanvullende-modellen/
            - https://data.crow.nl/imbor/aanvullend-metamodel/
